name: AkatsukiFE

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: List node_modules
        run: ls -la node_modules

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
        env:
          # 필요한 환경 변수를 여기에 추가합니다.
          NODE_ENV: production

      - name: Zip Artifacts
        run: zip -r deploy.zip dist server.js package.json Procfile

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init AkatsukiFE --platform node.js --region ap-northeast-2
          eb deploy AkatsukiFE-env

      - name: Check Environment Health
        run: |
          STATUS=$(aws elasticbeanstalk describe-environments --environment-names AkatsukiFE-env --query 'Environments[0].Health' --output text)
          if [ "$STATUS" != "Green" ]; then
            echo "Environment health is not 'Green'. Current status: $STATUS"
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Get Logs
        run: |
          eb logs AkatsukiFE-env
