name: AkatsukiFE

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r dist deploy/
          cp server.js package.json Procfile deploy/
          mkdir -p deploy/.ebextensions
          cat <<EOF > deploy/.ebextensions/nginx.config
          files:
            "/etc/nginx/conf.d/myapp.conf":
              mode: "000644"
              owner: root
              group: root
              content: |
                server {
                  listen 80;
                  server_name localhost;

                  access_log /var/log/nginx/access.log;
                  error_log /var/log/nginx/error.log;

                  location / {
                    proxy_pass http://localhost:8080;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                  }

                  location /static/ {
                    alias /usr/share/nginx/html/static/;
                  }

                  error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
                    root /usr/share/nginx/html;
                  }
                }
          container_commands:
            01_reload_nginx:
              command: "ln -sfn /etc/nginx/conf.d/myapp.conf /etc/nginx/sites-enabled/myapp && nginx -s reload"
          EOF
          cd deploy
          zip -r ../deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: AkatsukiFE
          environment_name: AkatsukiFE-env
          version_label: github-action-${{ github.run_id }}
          region: ap-northeast-2
          deployment_package: deploy.zip

      - name: Check Environment Health
        run: |
          STATUS=$(aws elasticbeanstalk describe-environments --environment-names AkatsukiFE-env --query 'Environments[0].Health' --output text)
          if [ "$STATUS" != "Green" ]; then
            echo "Environment health is not 'Green'. Current status: $STATUS"
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Get Logs
        run: |
          eb logs AkatsukiFE-env